hash-format = "sha256"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "d7a30358cb8314c296fec14e4ea74b8301edf093d6054dafac121e8fe9ac434f"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "bb3d9e5640c61e9d63cba49980846154de2509761607bfd7fbafd32ba502f910"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "1aaba088a650cc1499e1871cfa92f97e3d10a9d8c612fbd784b36c12382196de"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "2bcea8e16d358942a8f8b8cf6e39cc303d90fac29b1b3ecb8033bd214d4afa0f"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "440a806e54d48cd4c5ef447ff8f1a6cd9a99d53d02ab90d50204be9b31c2f30d"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "97f7c75ac9bf6ee2a4f15c0f1e3e4cd161f3d2e33f32ebf623811ac90b3c2a83"
metafile = true

[[files]]
file = "mods/dynamic-trees-biomes-o-plenty.pw.toml"
hash = "dfbe6bbfb2376cb1e0ffe1da8905c53257c85cd84f509027e56bef07574d0d1a"
metafile = true

[[files]]
file = "mods/dynamictrees.pw.toml"
hash = "1d29f0d2a87aa2f4f0e4c1f6c25e640516fc9a43c77b5d2405a426a80d279faa"
metafile = true

[[files]]
file = "mods/dynamictreesplus.pw.toml"
hash = "dfb8c790539d6136cc757a5afebb2156d15bf66dc927c4a172d3ddaa75cef896"
metafile = true

[[files]]
file = "mods/expanded-ecosphere.pw.toml"
hash = "425e6c28f8cde1a676002afc11d62a847d7ead47c4a345da8dc0f2f6dd58562c"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "71f185e62d546881244d4b5a213ebc3d2d6df14b0218c0e5dd6426fcb22cb55f"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "2e42b3a809ec9b027e23714e01c255fe5111a9d4cd58fad114dd0f2aa75c0d7e"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "adb67ada5c165ea4a43f4c3e53ffd61c90e21292596b5609d97e938f6e8e7b16"
metafile = true

[[files]]
file = "mods/mpalladium.pw.toml"
hash = "98815a8a24cf1eb227e1b6ae101a7416de0d18bd1d95d27c52906679c3cd5d76"
metafile = true

[[files]]
file = "mods/projecte.pw.toml"
hash = "26b6891625bf09317245200e3adb871cea00dbd41859d68cf57062544c0e6041"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "8df897c0f7831e919aa528c3c1e5239f39439c123d99761230ab2357132bad98"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "b85e8417e797be3fdae046c487eeda8f54cdc88f3f20e462e0e229f8dd734214"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "5c07edd0c8fe82e85efd6c027476ba54cf98291526803b74614c3436292e4ab6"
metafile = true

[[files]]
file = "mods/sodium-dynamic-lights.pw.toml"
hash = "82bb7cd6c8b68bb1831bb7c374bd316b6403cd01195d582f19c31076c908953a"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "75a60e6b443b351b7a4a78ffce7c71e44b3e20ca10c374aea1de516c785d6e2d"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "14117b94c456598c9acece143c7a0da3cf56d13182d035a74a2da8a52dd19cbd"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "6160cdcd8b686e90f72e76072ba96de7c5ae40460b3771401222ddebdee1d5ed"
metafile = true

[[files]]
file = "mods/toadlib.pw.toml"
hash = "8a46b1ad0c1eaa1f0a0d03bf71ccf53b5d706cc9095c31fb0e653f4cb4e03158"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "4bcf74d4569def60ca031d565350952c2edcc420f26278bc7997654a77b6fb4d"
metafile = true
